### PR TITLE
feat:build injection version

### PR DESCRIPTION
**Pull request by songzhibin97**
Use make all to automatically type version information into

### CODE REVIEW

**Comment by shenqidebaozi** [comment]
Is the go install or go get installation applicable?

**Comment by shenqidebaozi** [comment]
Note that it is a command line tool that needs to be pulled remotely

**Comment by songzhibin97** [comment]
> Add more commits by pushing to the `[feat-version-Inject](/songzhibin97/kratos/tree/feat-version-Inject)` branch on [songzhibin97/kratos](/songzhibin97/kratos).

It won't work if you don't use makefile

**Comment by Casper-Mars** [comment]
Hi~ Suppose a new tool is added, then the Makefile need to be modified. This requires extra work.

**Comment by songzhibin97** [comment]
> Hi~ Suppose a new tool is added, then the Makefile need to be modified. This requires extra work.




> 
Yes, I'll turn it off if I don't need it, and the external version doesn't seem to be in use.

**Comment by shenqidebaozi** [comment]
I don't think it makes sense

**Pull request closed without merging**
