### PR TITLE
fix(contrib): fix eureka server load too high  (#2545)

### LINKED ISSUE #2545: fix:Eureka Client刷新节点导致server负载过高
#### What happened:
问题1：目前刷新eureka client，从server端拉取节点数据频率过高，会导致Eureka server负载增高
问题2：服务注册Eureka后，采用异步协程接收节点信息的广播，减少启动时间
#### What you expected to happen:
降低刷新频率
#### Environment:
- Kratos version (use `kratos -v`):
- Go version (use `go version`):
- OS (e.g: `cat /etc/os-release`):
- Others:

### PR DESCRIPTION
**Pull request by weetime**
#### Which issue(s) this PR fixes (resolves / be part of):

fixes #2545

### CODE REVIEW

**Comment by shenqidebaozi** [comment]
Sorry, I didn't see how it solved the problem of high load

**Comment by yeqown** [comment]
https://github.com/go-kratos/kratos/blob/2cf82fa4a75cea70bd500561975b95659237d892/contrib/registry/eureka/register.go#L45-L60

https://github.com/go-kratos/kratos/blob/2cf82fa4a75cea70bd500561975b95659237d892/contrib/registry/eureka/eureka.go#L23-L50

looks like the `refresh` function with the default interval specified by `refreshTime` time.Duration(30)？

**Comment by weetime** [comment]
> fix default value time.Duration(30) to  time.Duration(30s). Client overwrite with WithRefresh().

**Comment by weetime** [comment]
https://github.com/go-kratos/kratos/blob/2cf82fa4a75cea70bd500561975b95659237d892/contrib/registry/eureka/register.go#L29-L31

**Review by shenqidebaozi — APPROVED** [review]

**Pull request merged**
