### PR TITLE
fix: support unicode punctuation in cmd/protoc-gen-go-errors

### LINKED ISSUE #1913: protoc-gen-go-errors convert wrongly when field with unicode punctuation.
#### What happened:
protoc-gen-go-errors convert wrongly when field with unicode punctuation.

#### What you expected to happen:
It can support field with unicode punctuation.

#### How to reproduce it (as minimally and precisely as possible):
```
func Test_case2Camel(t *testing.T) {
	type args struct {
		name string
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{
			name: "unicode_punctuation1",
			args: args{"go_go_\u2024go"},
			want: "GoGo\u2024Go",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := case2Camel(tt.args.name); got != tt.want {
				t.Errorf("input: %v, case2Camel() = %v, want %v", tt.args.name, got, tt.want)
			}
		})
	}
}
```

#### Anything else we need to know?:
[strings.Title bug in go1.16.x](https://cs.opensource.google/go/go/+/refs/tags/go1.6.4:src/strings/strings.go;l=492)
[strings.Title is Deprecated in go1.18](https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/strings/strings.go;l=715)

#### Environment:
- Kratos version (use `kratos -v`): v2.2.1
- Go version (use `go version`): v1.18
- OS (e.g: `cat /etc/os-release`): 20.04.4 LTS (Focal Fossa)
- Others:

### PR DESCRIPTION
**Pull request by pauky**
…f error.

The rule strings.Title uses for word boundaries does not handle Unicode punctuation properly.
reference: https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/strings/strings.go;l=715

Refs: #1913

#### Which issue(s) this PR fixes (resolves / be part of):

fixes #1913

### CODE REVIEW

**Review by tonybase — APPROVED** [review]

**Comment by tonybase** [comment]
please help to resolve the conflict, thanks

**Comment by pauky** [comment]
> please help to resolve the conflict, thanks

OK, I have resolved it.

**Comment by fifsky** [comment]
repeated  and have been fixed

https://github.com/go-kratos/kratos/pull/1919  
https://github.com/go-kratos/kratos/pull/1923

**Comment by pauky** [comment]
OK, I close this PR.

**Pull request closed without merging**
