### PR TITLE
fix: kratos proto server cmd method name bugfix (#2089)

### PR DESCRIPTION
**Pull request by raw34**
- add ucFirst function and unit test at cmd/kratos/internal/proto/server/server.go
- fix the [method name style bug ](https://github.com/go-kratos/kratos/issues/2089)

### CODE REVIEW

**Comment by Casper-Mars** [comment]
This would not solve the issue #2089 . Issue #2089 is about camel case and snake case.

**Comment by raw34** [comment]
> This would not solve the issue #2089 . Issue #2089 is about camel case and snake case.

this commit just fix the part2 problem, like this:


```
# proto
service OrderItems {
	rpc CreateOrderItems (CreateOrderItemsRequest) returns (CreateOrderItemsReply);
......
}
```

```
# wrong service
......

func (s *OrderItemsService) Createorderitems(ctx context.Context, req *pb.CreateOrderItemsRequest) (*pb.CreateOrderItemsReply, error) {
	return &pb.CreateOrderItemsReply{}, nil
}

.....
```

```
# right service

......

func (s *OrderItemsService) CreateOrderItems(ctx context.Context, req *pb.CreateOrderItemsRequest) (*pb.CreateOrderItemsReply, error) {
	return &pb.CreateOrderItemsReply{}, nil
}

.....
```

**Comment by Casper-Mars** [comment]
OH~Do you mean this PR is still working in progress?

**Comment by raw34** [comment]
> OH~Do you mean this PR is still working in progress?

the fact is i didn't find out the issue is about 2 problems, hah...

i can try to resolve the part1 problem some time later

**Comment by shenqidebaozi** [comment]
@raw34 https://github.com/songzhibin97/kratos/blob/4e100fcdeb4dd046f1430ecde1ca96fafb9584ff/cmd/kratos/internal/proto/server/server.go#L70

**Comment by shenqidebaozi** [comment]
It seems that the problem is caused by this modification

**Comment by raw34** [comment]
> It seems that the problem is caused by this modification

yes, it is. the modification fix another bug, but trigger this bug. and my commit can fix it.

**Comment by shenqidebaozi** [comment]
Has this PR been completed?

**Review by tonybase — APPROVED** [review]

**Review by haiyux — APPROVED** [review]

**Review by haiyux — APPROVED** [review]

**Pull request merged**
