### PR TITLE
refactor: metadata supports key corresponding to multiple values

### PR DESCRIPTION
**Pull request by ibrahimalbarghouthi**
Adding Add/Values func for transport and metadata layers, fixed tests a… #2771

### CODE REVIEW

**Review by tonybase — DISMISSED** [review]
LGTM

**Comment by tonybase** [comment]
@ibrahimalbarghouthi please fix lint

**Comment by ibrahimalbarghouthi** [comment]
@tonybase Done please merge

**Review by shenqidebaozi — APPROVED** [review]
LGTM

**Review by haiyux — APPROVED** [review]

**Pull request merged**
