### PR TITLE
fix:fix log caller error

### LINKED ISSUE #1520: log.DefaultCaller的caller不正确
#### What happened:
log库初始化caller方法，日志中显示的caller不正确
INFO caller=helper.go:51 msg=helper.info
DEBUG caller=main.go:13 msg=debug
WARN caller=proc.go:225 warn=warn
#### What you expected to happen:
INFO caller=main.go:12 msg=helper.info
DEBUG caller=main.go:13 msg=debug
WARN caller=main.to:14 warn=warn
#### How to reproduce it (as minimally and precisely as possible):
func main() {
	logger := log.With(log.DefaultLogger, "caller", log.DefaultCaller)
	help := log.NewHelper(logger)
	help.Info("helper.info")
	help.Debug("debug")
	help.Log(log.LevelWarn,"warn","warn")
}
#### Anything else we need to know?:
创建的logger不要先调用Log方法
#### Environment:
- Kratos version (use `kratos -v`):v2.0.5
- Go version (use `go version`):1.16.6
- OS (e.g: `cat /etc/os-release`):macOS Big Sur 11.6
- Others:

### PR DESCRIPTION
**Pull request by haiyux**
#### Which issue(s) this PR fixes (resolves / be part of):

fixes #1520

### CODE REVIEW

**Review by tonybase — APPROVED** [review]

**Review by elvizlai — COMMENTED** [review]
😂...this code behaves same as before

**Comment by haiyux** [comment]
> 😂...this code behaves same as before

Please learn closure.

**Comment by elvizlai** [comment]
func param `depth` it's a copy. Anyway `Please learn closure.`

**Comment by haiyux** [comment]
> func param `depth` it's a copy. Anyway `Please learn closure.`

```go
package main

import "fmt"

func main() {
	a := test1(1)
	a()
	a()
	b := test2(1)
	b()
	b()
}

func test1(n int) func() {
	return func() {
		n++
		fmt.Println("test1", n)
	}
}

func test2(n int) func() {
	return func() {
		n := n
		n++
		fmt.Println("test2", n)
	}
}

```
Do you think the two results are the same? If you don't know, go and study.

**Comment by elvizlai** [comment]
Sorry my mistake, the Caller should always using same init param.

**Pull request merged**
