### PR TITLE
feat(registry): support discovery registry center

### LINKED ISSUE #1472: [Feature] support discovery registry center
Please see the FAQ in our main README.md before submitting your issue.

### What problem is the feature used to solve?

We hope to add `discovery` registry center `registry.Registrar`  to Kratos framework.

### Requirements description of the feature

* support `discovery` registry center works as `registry.Registrar` in kratos

### References

* https://github.com/bilibili/discovery

### PR DESCRIPTION
**Pull request by yeqown**
#### Description (what this PR does / why we need it):

* support discovery registry center
* add example for using `discovery` registry center 

#### Which issue(s) this PR fixes (resolves / be part of):

resolves #1472 

#### Other special notes for reviewer:

I need some time to refactor code style, any advices and code review can help this work, thanks ~

### CODE REVIEW

**Comment by seasrain** [comment]
feat #1472

**Comment by yeqown** [comment]
review plz ~

**Comment by longXboy** [comment]
Why not reference the original bilibili/discovery SDK and wrap it to implement kratos interface？

**Comment by yeqown** [comment]
@longXboy 

1. The old package（discovery/naming） imports kratos@v1 package, it's  not wise to use old version of kratos. https://github.com/bilibili/discovery/blob/1e12d5c0080ecd7ce97ab78076ef36dda8d56a1a/naming/client.go#L16-L19
2. Personal preference: the old package use std http client which is no friendly to human and makes the code fetid and wordy.
3. I'm not sure of that is it workable wraps `bilibili/discovery SDK` to implement kratos@v2 `registry.Registrar` and `registry.Discovery` interfaces.

**Review by longXboy — APPROVED** [review]

**Comment by longXboy** [comment]
> @longXboy
> 
> 1. The old package（discovery/naming） imports kratos@v1 package, it's  not wise to use old version of kratos. https://github.com/bilibili/discovery/blob/1e12d5c0080ecd7ce97ab78076ef36dda8d56a1a/naming/client.go#L16-L19
> 2. Personal preference: the old package use std http client which is no friendly to human and makes the code fetid and wordy.
> 3. I'm not sure of that is it workable wraps `bilibili/discovery SDK` to implement kratos@v2 `registry.Registrar` and `registry.Discovery` interfaces.

LGTM

**Pull request merged**
