### PR TITLE
fix: Logging middleware will be missing trace_id when logger is filterlogger

### PR DESCRIPTION
**Pull request by CuiGou**
#### Description (what this PR does / why we need it):
修复启用链路追逐后log中间件使用logfilter后,打印的请求日志中缺失trace.id值,如下
```
INFO ts=2022-12-08T15:46:40+08:00 caller=log/log.go:30 trace.id= kind=server component=grpc operation=/video.basics.v1.notification.NotificationSrv/GetNotification args=webmaster_id:1595665043859443712 limit:20 code=0 reason= stack= latency=0.000850499
```

#### Which issue(s) this PR fixes (resolves / be part of):

fix/logfilter #2570 

#### Other special notes for the reviewers:

**应该在log.WithContext()方法中进一步断言logger类型,并取出初始logger的prefix**

### CODE REVIEW

**Comment by shenqidebaozi** [comment]
@Cynicism-zx please fix lint failed

**Comment by Cynicism-zx** [comment]
@shenqidebaozi fixed

**Comment by stonelgh** [comment]
@Cynicism-zx @shenqidebaozi Could you please comment?

**Comment by freezeChen** [comment]
don't simple to using origin logger, It will cause the Filter not working.

**Pull request closed without merging**
