### PR TITLE
feat(middleware/validate): replace PGV by protovalidate-go

### PR DESCRIPTION
**Pull request by perriea**
#### Description (what this PR does / why we need it):
- [x] Replace PGV by protovalidate-go on `validate` package,
- [x] Remove PGV on `kratos` cli

#### Which issue(s) this PR fixes (resolves / be part of):
#3081 

**WARNING** It's a breaking change !

### CODE REVIEW

**Comment by perriea** [comment]
@shenqidebaozi we have everything, but I don't know how to test validation with this new format. If you have an idea...

**Comment by perriea** [comment]
@shenqidebaozi Let me remind you, any opinion ?

**Comment by perriea** [comment]
> Any update for this PR?

This change is important, but I have no answer... Sorry

**Comment by shenqidebaozi** [comment]
Please fix the issue of github action line failure first

**Comment by shenqidebaozi** [comment]
Also, should we treat PGV as some kind of implementation, with the standard interface in validate

**Comment by perriea** [comment]
> Please fix the issue of github action line failure first

We have a problem on the CI, I have an error unrelated to my modifications (contrib)...

**Comment by shenqidebaozi** [comment]
Your code changes contain many contrib changes. You may consider resubmitting a PR or abandoning other changes and only modifying PGV

**Comment by shenqidebaozi** [comment]
@perriea I see that this PR has been closed. Is there any problem?

**Comment by shenqidebaozi** [comment]
The current PR only needs to remove additional modifications. Also, can the `validate` interface be retained and PGV be used as a new implementation. What do you think?

**Comment by perriea** [comment]
> @perriea I see that this PR has been closed. Is there any problem?

One of my colleagues accidentally deleted my fork... this action closed my PR...

**Pull request closed without merging**
