### PR TITLE
fix(cmd/protoc-gen-go-http): Fix when replacement rule is not ending

### PR DESCRIPTION
**Pull request by bakjos**
#### Description (what this PR does / why we need it):
This PR is a continuation of https://github.com/go-kratos/kratos/pull/1704, to fix https://github.com/go-kratos/kratos/issues/1653. When the path was `"/v1/{parent=shelves/*}/books"` the matching path was `"/v1/{parent:shelves/*}"` instead of `"/v1/{parent:shelves/*}/books"` so it was matching any URL including `/shelves/*` and not only those with `/shelves/*/book`

#### Which issue(s) this PR fixes (resolves / be part of):

fixes # https://github.com/go-kratos/kratos/issues/1653

### CODE REVIEW

**Comment by bakjos** [comment]
@longXboy I think the old PR did not fix https://github.com/go-kratos/kratos/issues/1653

**Review by tonybase — APPROVED** [review]

**Comment by shenqidebaozi** [comment]
@bakjos Hello brother I wonder if you have tried to register the above routes with MUX in the actual scenario. Can you correctly match the corresponding paths? When I locally test and register the above route, the request returns 404. I don't know where the difference is.

**Comment by shenqidebaozi** [comment]
@bakjos 
- https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#http
- https://cloud.google.com/apis/design/standard_methods
image

**Comment by shenqidebaozi** [comment]
It's my problem. I'm sorry

**Review by shenqidebaozi — APPROVED** [review]
LGTM

**Pull request merged**
