### PR TITLE
fix: change the working directory of the command

### LINKED ISSUE #2519: kratos run目录问题
kratos run运行之后，如果代码里有生成文件或者目录等操作，会被创建到相对于main.go的目录，而不是相对于项目根目录。
比如我的项目根目录叫testProject
main文件在testProject/cmd/server/main.go
如果执行kratos run运行后
我现在使用os.OpenFile()创建一个文件test.log
这个文件就会生成在 testProject/cmd/server/ 目录
而不是 testProject/ 目录

### PR DESCRIPTION
**Pull request by starmilkxin**
Refs #2519

#### Description (what this PR does / why we need it):

This pr changes the working directory of the command run, so that the file creation operation is relative to the project root directory.

#### Which issue(s) this PR fixes (resolves / be part of):

fixes #2519

### CODE REVIEW

**Comment by shenqidebaozi** [comment]
I think we should add a work configuration directly instead of modifying the existing logic

**Comment by starmilkxin** [comment]
> I think we should add a work configuration directly instead of modifying the existing logic

Could you be more specific? Is it similar to adding a configuration item to the source code to determine whether the kratos working directory is the project root directory, or adding an argument after "kratos run" ?

**Comment by shenqidebaozi** [comment]
kratos run -work=xxxxx

**Comment by starmilkxin** [comment]
please code review @shenqidebaozi

**Review by longXboy — APPROVED** [review]

**Review by Cluas — APPROVED** [review]

**Pull request merged**
